// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://mkqwnfofyttnhodafdqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcXduZm9meXR0bmhvZGFmZHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjQzNjMsImV4cCI6MjA2NjA0MDM2M30.5TQz23GkMKtbimGDzU79s6O-P4jz0tw8NT7uMmWu8O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
