// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdxsqakwajhglrwcmhrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkeHNxYWt3YWpoZ2xyd2NtaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTUxMTQsImV4cCI6MjA2MzQzMTExNH0.j4iZIZIRY9zzrgMMhZ23ziIuzCURZyrohU9ob7ROIiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);